export const precios = [
	{
		modelo: "180 S",
		familia: "180",
		marca: "Benelli",
		precio: 3630336,
		sinonimos: [""],
		cilindradas: 180,
		url: "https://www.benelli.com/ar-es/products/180s",
	},
	{
		modelo: "251 S",
		familia: "251",
		marca: "Benelli",
		precio: 5274076,
		sinonimos: [""],
		cilindradas: 250,
		url: "https://www.benelli.com/ar-es/products/251s",
	},
	{
		modelo: "302 S",
		familia: "302",
		marca: "Benelli",
		precio: 7991265,
		sinonimos: [""],
		cilindradas: 300,
		url: "https://www.benelli.com/ar-es/products/302s",
	},
	{
		modelo: "502 C",
		familia: "502",
		marca: "Benelli",
		precio: 12523387,
		sinonimos: [""],
		cilindradas: 500,
		url: "https://www.benelli.com/ar-es/products/502c",
	},
	{
		modelo: "752 S",
		familia: "752",
		marca: "Benelli",
		precio: 15789626,
		sinonimos: [""],
		cilindradas: 750,
		url: "https://www.benelli.com/ar-es/products/752s-2",
	},
	{
		modelo: "IMPERIALE 400",
		familia: "IMPERIALE",
		marca: "Benelli",
		precio: 6925590,
		sinonimos: ["Benelli 400"],
		cilindradas: 400,
		url: "https://www.benelli.com/ar-es/products/imperiale-400",
	},
	{
		modelo: "LEONCINO 250",
		familia: "LEONCINO",
		marca: "Benelli",
		precio: 5750916,
		sinonimos: ["Benelli 250"],
		cilindradas: 250,
		url: "https://www.benelli.com/ar-es/products/leoncino-250",
	},
	{
		modelo: "LEONCINO 500 (todas AM2022)",
		familia: "LEONCINO",
		marca: "Benelli",
		precio: 9741241,
		sinonimos: ["Benelli 500"],
		cilindradas: 500,
		url: "https://www.benelli.com/ar-es/products/leoncino-500",
	},
	{
		modelo: "LEONCINO 500 TRAIL",
		familia: "LEONCINO",
		marca: "Benelli",
		precio: 11323507,
		sinonimos: ["Benelli 500", "TRAIL"],
		cilindradas: 500,
		url: "https://www.benelli.com/ar-es/products/leoncino-500-trail-2",
	},
	{
		modelo: "TNT 15",
		familia: "TNT",
		marca: "Benelli",
		precio: 2357988,
		sinonimos: ["Benelli 15"],
		cilindradas: 150,
		url: "https://www.benelli.com/ar-es/products/tnt-15",
	},
	{
		modelo: "TNT 600i ABS nueva",
		familia: "TNT",
		marca: "Benelli",
		precio: 16900626,
		sinonimos: ["Benelli 600"],
		cilindradas: 600,
		url: "https://www.benelli.com/ar-es/products/tnt600i",
	},
	{
		modelo: "TRK 251 ABS",
		familia: "TRK",
		marca: "Benelli",
		precio: 6195228,
		sinonimos: ["Benelli 251"],
		cilindradas: 250,
		url: "https://www.benelli.com/ar-es/products/trk-251",
	},
	{
		modelo: "TRK 502 NEW",
		familia: "TRK",
		marca: "Benelli",
		precio: 12423397,
		sinonimos: [""],
		cilindradas: 500,
		url: "https://www.benelli.com/ar-es/products/trk-502-2020",
	},
	{
		modelo: "TRK 502-X NEW",
		familia: "TRK",
		marca: "Benelli",
		precio: 14033236,
		sinonimos: [""],
		cilindradas: 500,
		url: "https://www.benelli.com/ar-es/products/trk-502-x",
	},
	{
		modelo: "KEEWAY K-LIGHT 202",
		familia: "K-LIGHT",
		marca: "Keeway",
		precio: 3073936,
		sinonimos: ["LIGHT", "202"],
		cilindradas: 200,
		url: "https://www.keeway.com/ar-es/products/k-light-202",
	},
	{
		modelo: "RK 150",
		familia: "RK",
		marca: "Keeway",
		precio: 2002926,
		sinonimos: ["Keeway 150"],
		cilindradas: 150,
		url: "https://www.keeway.com/ar-es/products/rk-150",
	},
	{
		modelo: "BLITZ 110 V8 START",
		familia: "Blitz",
		marca: "Motomel",
		precio: 1049946,
		sinonimos: ["110", "V8"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-blitz-110-start.pdf",
	},
	{
		modelo: "BLITZ 110 V8 FULL ONE - B1 - ALEACION DISCO - NEW",
		familia: "Blitz",
		marca: "Motomel",
		precio: 1145495,
		sinonimos: ["110", "V8", "ONE"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-blitz-110-full.pdf",
	},
	{
		modelo: "BLITZ 110 V8 BASE ONE - B1 Automatica - NEW",
		familia: "Blitz",
		marca: "Motomel",
		precio: 1145953,
		sinonimos: ["110", "V8", "ONE"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-blitz-110-automatica.pdf",
	},
	{
		modelo: "BLITZ 110 V8 PLUS",
		familia: "Blitz",
		marca: "Motomel",
		precio: 1303947,
		sinonimos: ["110", "V8", "PLUS"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-blitz-plus.pdf",
	},
	{
		modelo: "BLITZ 110 V8 TUNNING NEW",
		familia: "Blitz",
		marca: "Motomel",
		precio: 1412415,
		sinonimos: ["110", "V8", "TUNNING", "TUNING", "TUNNIN", "TUNIN"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-blitz-110-tunning.pdf",
	},
	{
		modelo: "CG 150 S2 START",
		familia: "CG",
		marca: "Motomel",
		precio: 1391562,
		sinonimos: ["S2"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-s2-150-start.pdf",
	},
	{
		modelo: "CG 150 S2 FULL (aleac / disco)",
		familia: "CG",
		marca: "Motomel",
		precio: 1651950,
		sinonimos: ["S2"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-s2-150-aleacion.pdf",
	},
	{
		modelo: "DLX 110 DELUXE",
		familia: "DLX",
		marca: "Motomel",
		precio: 1049946,
		sinonimos: ["110", "DELUXE"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-dlx-110.pdf",
	},
	{
		modelo: "MAX 110 A/E",
		familia: "MAX",
		marca: "Motomel",
		precio: 1396475,
		sinonimos: ["110"],
		cilindradas: 110,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-max-110.pdf",
	},
	{
		modelo: "MOTOCARGO 200 CC NEW",
		familia: "MOTOCARGO",
		marca: "Motomel",
		precio: 2390916,
		sinonimos: ["CARGO"],
		cilindradas: 200,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-motocargo-200.pdf",
	},
	{
		modelo: "SIRIUS 190 NUEVO PRODUCTO",
		familia: "SIRIUS",
		marca: "Motomel",
		precio: 2233737,
		sinonimos: ["190"],
		cilindradas: 190,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-sirius-190.pdf",
	},
	{
		modelo: "SKUA 125 X-TREME",
		familia: "SKUA",
		marca: "Motomel",
		precio: 1481699,
		sinonimos: ["Motomel 125", "X-TREME", "XTREME"],
		cilindradas: 125,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-skua-125.pdf",
	},
	{
		modelo: "SKUA 150 NEW GENERATION",
		familia: "SKUA",
		marca: "Motomel",
		precio: 1739539,
		sinonimos: ["Motomel 150", "New Generation"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-skua-150.pdf",
	},
	{
		modelo: "SKUA 150 SILVER EDITION",
		familia: "SKUA",
		marca: "Motomel",
		precio: 2047596,
		sinonimos: ["Motomel 150", "Silver"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-skua-150-silver.pdf",
	},
	{
		modelo: "SKUA 250 BASE NEW",
		familia: "SKUA",
		marca: "Motomel",
		precio: 2356406,
		sinonimos: ["Motomel 250"],
		cilindradas: 250,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-skua-250.pdf",
	},
	{
		modelo: "SKUA 250 ADVENTURE NUEVO MODELO",
		familia: "SKUA",
		marca: "Motomel",
		precio: 3353939,
		sinonimos: ["Motomel 250", "Adventure"],
		cilindradas: 250,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-skua-250-adventure.pdf",
	},
	{
		modelo: "STRATO 150 EURO",
		familia: "STRATO",
		marca: "Motomel",
		precio: 1993082,
		sinonimos: ["Motomel 150", "Euro"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-strato-euro-150-led.pdf",
	},
	{
		modelo: "STRATO 150 ALPINO",
		familia: "STRATO",
		marca: "Motomel",
		precio: 2103179,
		sinonimos: ["Motomel 150", "Alpino"],
		cilindradas: 150,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-strato-alpino-150.pdf",
	},
	{
		modelo: "TARPAN 200 RUN ER - BICICLETA",
		familia: "BICICLETA",
		marca: "Motomel",
		precio: 447569,
		sinonimos: ["Tarpan"],
		cilindradas: "",
		url: "",
	},
	{
		modelo: "XMM 250 NUEVA",
		familia: "XMM",
		marca: "Motomel",
		precio: 2783966,
		sinonimos: ["Motomel 250"],
		cilindradas: 250,
		url: "https://motomel.com.ar/fichas-tecnicas/ficha-tecnica-xmm-250.pdf",
	},
	{
		modelo: "AX 100",
		familia: "AX",
		marca: "Suzuki",
		precio: 1586256,
		sinonimos: ["Suzuki 100"],
		cilindradas: 100,
		url: "https://suzukimotosarg.com.ar/wp-content/uploads/2021/09/Ficha-tecnica-AX100-Back.pdf",
	},
	{
		modelo: "GN 125",
		familia: "GN",
		marca: "Suzuki",
		precio: 2271696,
		sinonimos: ["Suzuki 125"],
		cilindradas: 125,
		url: "https://suzukimotosarg.com.ar/products/gn125f/",
	},
	{
		modelo: "GSX 125",
		familia: "GSX",
		marca: "Suzuki",
		precio: 2394606,
		sinonimos: ["Suzuki 125"],
		cilindradas: 125,
		url: "https://suzukimotosarg.com.ar/wp-content/uploads/2023/05/Ficha-tecnica-GSX-125R.pdf",
	},
	{
		modelo: "CITYCOM 300 i",
		familia: "CITYCOM",
		marca: "SYM",
		precio: 7151407,
		sinonimos: ["City", "Sym 300"],
		cilindradas: 300,
		url: "https://sym-argentina.com.ar/modelos/citycom-s-300i/",
	},
];